import Head from 'next/head';
import Link from 'next/link';

import { getAllPosts } from '../lib/api';

export default function Home({ allPosts }) {
  return (
    <div>
      <Head>
        <title>Heimdallr&apos;s Blog</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <header>
        <h1>Heimdallr&apos;s Blog</h1>
        <h2>Tagline goes here</h2>
      </header>

      <main>
        <ul>
          {allPosts.map(({ slug, title, date }) => (
            <Link key={slug} href={`/posts/${slug}`}>
              <li>
                {title} - {date}
              </li>
            </Link>
          ))}
        </ul>
      </main>

      <footer>Footer goes here</footer>
    </div>
  );
}

export const getStaticProps = async () => {
  const allPosts = getAllPosts();

  return {
    props: { allPosts },
  };
};
